version: '3.3'

services:
  mongodb:
    image: mongo
    container_name: 'my-mongo-container'
    ports:
      - '27017:27017'
    volumes:
      - './seed.js:/docker-entrypoint-initdb.d/mongo-init.js:ro'